version: 0.0
os: linux
files:
  - source: s3://mayanna-code-deploy/jars/target/SpringBootEc2CodeDeployDemo-0.0.1-SNAPSHOT.jar
    destination: ~/springbootjars/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
